# Cloudflare Pages + D1. Sustituye database_id por el de tu instancia D1.
name = "bebe-sueno"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "sueno"
database_id = "fd6c0aab-3ab0-496f-b636-3ab5e554eb89"
